// Example code that deserializes and serializes the model.
// extern crate serde;
// #[macro_use]
// extern crate serde_derive;
// extern crate serde_json;
//
// use generated_module::Gamestate;
//
// fn main() {
//     let json = r#"{"answer": 42}"#;
//     let model: Gamestate = serde_json::from_str(&json).unwrap();
// }

use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Gamestate {
    pub slave_market_manager: Box<Option<serde_json::Value>>,
    pub country: Box<Option<serde_json::Value>>,
    pub leaders: Box<Option<serde_json::Value>>,
    pub espionage_assets: Box<Option<serde_json::Value>>,
    pub flags: Box<Option<serde_json::Value>>,
    pub war: Box<Option<serde_json::Value>>,
    pub orbital_line: Box<Option<serde_json::Value>>,
    pub name: Box<Option<serde_json::Value>>,
    pub random_name_database: Box<Option<serde_json::Value>>,
    pub version: Box<Option<serde_json::Value>>,
    pub saved_event_target: Box<Option<serde_json::Value>>,
    pub used_species_names: Box<Option<serde_json::Value>>,
    pub missile: Box<Option<serde_json::Value>>,
    pub required_dlcs: Box<Option<serde_json::Value>>,
    pub natural_wormholes: Box<Option<serde_json::Value>>,
    pub resolution: Box<Option<serde_json::Value>>,
    pub planets: Box<Option<serde_json::Value>>,
    pub fleet: Box<Option<serde_json::Value>>,
    pub army: Box<Option<serde_json::Value>>,
    pub last_created_species_ref: Box<Option<serde_json::Value>>,
    pub buildings: Box<Option<serde_json::Value>>,
    pub used_symbols: Box<Option<serde_json::Value>>,
    pub last_created_country: Box<Option<serde_json::Value>>,
    pub galaxy: Box<Option<serde_json::Value>>,
    pub used_species_portrait: Box<Option<serde_json::Value>>,
    pub galactic_community: Box<Option<serde_json::Value>>,
    pub strike_craft: Box<Option<serde_json::Value>>,
    pub last_refugee_country: Box<Option<serde_json::Value>>,
    pub fired_event_ids: Box<Option<serde_json::Value>>,
    pub player: Box<Option<serde_json::Value>>,
    pub truce: Box<Option<serde_json::Value>>,
    pub last_event_id: Box<Option<serde_json::Value>>,
    pub agreements: Box<Option<serde_json::Value>>,
    pub last_created_army: Box<Option<serde_json::Value>>,
    pub last_created_leader: Box<Option<serde_json::Value>>,
    pub spy_networks: Box<Option<serde_json::Value>>,
    pub saved_leaders: Box<Option<serde_json::Value>>,
    pub galactic_object: Box<Option<serde_json::Value>>,
    pub name_list: Box<Option<serde_json::Value>>,
    pub last_created_system: Box<Option<serde_json::Value>>,
    pub construction: Box<Option<serde_json::Value>>,
    pub galaxy_radius: Box<Option<serde_json::Value>>,
    pub debris: Box<Option<serde_json::Value>>,
    pub trade_deal: Box<Option<serde_json::Value>>,
    pub sectors: Box<Option<serde_json::Value>>,
    pub espionage_operations: Box<Option<serde_json::Value>>,
    pub first_contacts: Box<Option<serde_json::Value>>,
    pub additional_crisis_strength: Box<Option<serde_json::Value>>,
    pub last_created_pop: Box<Option<serde_json::Value>>,
    pub date: Box<Option<serde_json::Value>>,
    pub archaeological_sites: Box<Option<serde_json::Value>>,
    pub random_log_day: Box<Option<serde_json::Value>>,
    pub tick: Box<Option<serde_json::Value>>,
    pub situations: Box<Option<serde_json::Value>>,
    pub deposit: Box<Option<serde_json::Value>>,
    pub random_seed: Box<Option<serde_json::Value>>,
    pub megastructures: Box<Option<serde_json::Value>>,
    pub pop: Box<Option<serde_json::Value>>,
    pub last_notification_id: Box<Option<serde_json::Value>>,
    pub bypasses: Box<Option<serde_json::Value>>,
    pub trade_routes_manager: Box<Option<serde_json::Value>>,
    pub last_created_fleet: Box<Option<serde_json::Value>>,
    pub dummy_species: Box<Option<serde_json::Value>>,
    pub global_ship_design: Box<Option<serde_json::Value>>,
    pub ship_design: Box<Option<serde_json::Value>>,
    pub last_killed_country_name: Box<Option<serde_json::Value>>,
    pub version_control_revision: Box<Option<serde_json::Value>>,
    pub open_player_event_selection_history: Box<Option<serde_json::Value>>,
    pub used_color: Box<Option<serde_json::Value>>,
    pub starbase_mgr: Box<Option<serde_json::Value>>,
    pub random_count: Box<Option<serde_json::Value>>,
    pub rim_galactic_objects: Box<Option<serde_json::Value>>,
    pub clusters: Box<Option<serde_json::Value>>,
    pub last_created_design: Box<Option<serde_json::Value>>,
    pub last_diplo_action_id: Box<Option<serde_json::Value>>,
    pub species_db: Box<Option<serde_json::Value>>,
    pub message: Box<Option<serde_json::Value>>,
    pub fleet_template: Box<Option<serde_json::Value>>,
    pub ships: Box<Option<serde_json::Value>>,
    pub last_created_ship: Box<Option<serde_json::Value>>,
    pub federation: Box<Option<serde_json::Value>>,
    pub ground_combat: Box<Option<serde_json::Value>>,
    pub trade_routes: Box<Option<serde_json::Value>>,
    pub system_initializer_counter: Box<Option<serde_json::Value>>,
    pub ambient_object: Box<Option<serde_json::Value>>,
    pub market: Box<Option<serde_json::Value>>,
    pub last_created_ambient_object: Box<Option<serde_json::Value>>,
    pub council_positions: Box<Option<serde_json::Value>>,
    #[serde(default)]
    _ignore: Option<serde_json::Value>,
}
